name: Latest Blogs

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs regularly
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Latest Blogs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instell packages
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run
      run: |
        python scripts/update_latest_blogs.py

    - name: Check Diff
      id: diff
      run: |
        git diff --name-only --exit-code
      continue-on-error: true

    - name: Commit files
      run: |
        git config --local user.name 'naoki'
        git config --local user.email 'u429561d@ecs.osaka-u.ac.jp'
        git add README.md
        git commit -m '🔄 auto: update latest blogs'
        git push
      if: steps.diff.outcome == 'failure'
